name: CMake

on:
  push:
    tags:
      - 'v*'

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  multi_os:
    strategy:
      matrix:
        os: [ubuntu-latest]
        #        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
    
    - name: Install Qt
      run: sudo apt install qtbase5-dev


    - name: Configure CMake
      run: cmake -B build -DWITH_CCACHE=OFF -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DWITH_QT5=ON

        #- name: Build
      #run: cmake --build build --config ${{env.BUILD_TYPE}} -j 4

    - name: Build
      run: make -C build install -j 4

    - name: Package
      run: bash -c "cd build && ../script_create_bin_dist.sh linux"

    - name: Upload binaries to release
      uses: softprops/action-gh-release@v1
      with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: build/micmac_linux.tgz

